"""Cambio de proveedor_id a color en la tabla accesorio

Revision ID: 3eaef1be8c07
Revises: 825f9069f4be
Create Date: 2024-09-09 18:20:41.708888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eaef1be8c07'
down_revision = '825f9069f4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=30), nullable=False))
        batch_op.drop_constraint('accesorio_ibfk_2', type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.alter_column('costo',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.alter_column('costo',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('accesorio_ibfk_2', 'proveedor', ['proveedor_id'], ['id'])
        batch_op.drop_column('color')

    # ### end Alembic commands ###
