"""empty message

Revision ID: 4b362b69b182
Revises: dd44f429de03
Create Date: 2024-08-12 12:46:06.286795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b362b69b182'
down_revision = 'dd44f429de03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'modelo', ['modelo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('modelo_id')

    # ### end Alembic commands ###
