"""Renombrar columna en Equipo

Revision ID: 4e38066bed95
Revises: 4b362b69b182
Create Date: 2024-08-16 21:52:30.097345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e38066bed95'
down_revision = '4b362b69b182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('modelo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.alter_column('pais_origen',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)
        batch_op.alter_column('pais_origen',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.alter_column('modelo_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
