"""empty message

Revision ID: 825f9069f4be
Revises: b973247b4d56
Create Date: 2024-09-09 12:48:49.022902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825f9069f4be'
down_revision = 'b973247b4d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint('equipo_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('equipo_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'modelo', ['modelo_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'marca', ['marca_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('equipo_ibfk_2', 'marca', ['marca_id'], ['id'])
        batch_op.create_foreign_key('equipo_ibfk_3', 'modelo', ['modelo_id'], ['id'])

    # ### end Alembic commands ###
