"""Agregar tablas Proveedor, Stock, Accesorio

Revision ID: ca17873cb355
Revises: 70e6093a57f3
Create Date: 2024-08-17 16:29:43.955188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca17873cb355'
down_revision = '70e6093a57f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accesorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=False),
    sa.Column('ubicacion_almacen', sa.String(length=100), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('accesorio')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
